### ISSUE TITLE
Keyboard shortcut to center the image

### ISSUE THREAD

**Issue by LuciusofLegend** [Orama-Interactive/Pixelorama-Docs#69]
I was just trying out pixelorama, and I accidentally zoomed away from the starting position, and it just occurred to me it would be nice to have a way to quickly return to it.  Just a little idea :D

**Comment by Variable-ind** [comment]
Hy :wave:, i know it's very late but this is already possible go to zoom tool and press fit to frame
![Screenshot from 2024-04-18 23-22-43](https://github.com/Orama-Interactive/Pixelorama-Docs/assets/77773850/bffaafca-3249-4e1f-9bc6-76434ed525f4)
